services:
  db:
    image: postgres:15
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    env_file:
      - .env
    environment:
      - TZ=Europe/Rome
      - PGTZ=Europe/Rome

  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - .:/code
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - "127.0.0.1:8001:8000"
    shm_size: '2gb'
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Rome
    depends_on:
      - db

  scheduler:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    command: python manage.py run_scheduler
    volumes:
      - .:/code
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    shm_size: '2gb'
    environment:
      - PYTHONUNBUFFERED=1
      - TZ=Europe/Rome
    depends_on:
      - db

volumes:
  postgres_data:
