# Generated by Django 6.0.1 on 2026-01-23 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfiloAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('peso', models.FloatField(default=70.0, help_text='In kg')),
                ('eta', models.IntegerField(default=30)),
                ('fc_riposo', models.IntegerField(default=60, help_text='Battiti a riposo')),
                ('fc_max', models.IntegerField(default=190, help_text='Battiti massimi')),
                ('vo2max_attuale', models.FloatField(blank=True, null=True)),
                ('ultima_analisi_ai', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_activity_id', models.BigIntegerField(unique=True)),
                ('data', models.DateTimeField()),
                ('distanza', models.FloatField(help_text='In metri')),
                ('durata', models.IntegerField(help_text='In secondi')),
                ('passo_medio', models.CharField(max_length=10)),
                ('fc_media', models.IntegerField(blank=True, null=True)),
                ('fc_max_sessione', models.IntegerField(blank=True, null=True)),
                ('dislivello', models.FloatField(default=0.0)),
                ('vo2max_stimato', models.FloatField(blank=True, null=True)),
                ('analisi_tecnica_ai', models.TextField(blank=True, null=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessioni', to='atleti.profiloatleta')),
            ],
            options={
                'verbose_name_plural': 'Attività',
            },
        ),
    ]
