# Generated by Django 6.0.1 on 2026-01-23 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='cadenza_media',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attivita',
            name='potenza_media',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attivita',
            name='sforzo_relativo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attivita',
            name='zone_cardiache',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
