# Generated by Django 6.0.1 on 2026-01-23 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0002_attivita_cadenza_media_attivita_potenza_media_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='battito_riposo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
