# Generated by Django 6.0.1 on 2026-01-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0003_attivita_battito_riposo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='fc_massima_teorica',
            field=models.IntegerField(default=190),
        ),
    ]
