# Generated by Django 6.0.1 on 2026-01-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0004_attivita_fc_massima_teorica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attivita',
            name='fc_massima_teorica',
        ),
        migrations.AddField(
            model_name='profiloatleta',
            name='fc_massima_teorica',
            field=models.IntegerField(default=190),
        ),
    ]
