# Generated by Django 6.0.1 on 2026-01-23 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0005_remove_attivita_fc_massima_teorica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='tipo_attivita',
            field=models.CharField(default='Run', max_length=20),
        ),
    ]
