# Generated by Django 6.0.1 on 2026-01-24 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0006_attivita_tipo_attivita'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloatleta',
            name='data_ultima_analisi',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='profiloatleta',
            name='ultima_analisi_ai',
            field=models.TextField(blank=True, null=True),
        ),
    ]
