# Generated by Django 6.0.1 on 2026-01-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0007_profiloatleta_data_ultima_analisi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloatleta',
            name='data_aggiornamento_indici',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profiloatleta',
            name='indice_itra',
            field=models.IntegerField(default=0, verbose_name='ITRA Index'),
        ),
        migrations.AddField(
            model_name='profiloatleta',
            name='indice_utmb',
            field=models.IntegerField(default=0, verbose_name='UTMB Index'),
        ),
        migrations.AlterField(
            model_name='profiloatleta',
            name='fc_riposo',
            field=models.IntegerField(blank=True, help_text='Battiti a riposo', null=True),
        ),
        migrations.AlterField(
            model_name='profiloatleta',
            name='peso',
            field=models.FloatField(blank=True, help_text='In kg', null=True),
        ),
    ]
