# Generated by Django 6.0.1 on 2026-01-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0008_profiloatleta_data_aggiornamento_indici_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiloatleta',
            name='vo2max_attuale',
        ),
        migrations.AddField(
            model_name='profiloatleta',
            name='vo2max_stima_statistica',
            field=models.FloatField(blank=True, null=True, verbose_name='VO2max Stima (Trail+Strada)'),
        ),
        migrations.AddField(
            model_name='profiloatleta',
            name='vo2max_strada',
            field=models.FloatField(blank=True, null=True, verbose_name='VO2max Solo Strada'),
        ),
    ]
