# Generated by Django 6.0.1 on 2026-01-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0009_remove_profiloatleta_vo2max_attuale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloatleta',
            name='immagine_profilo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
