# Generated by Django 6.0.1 on 2026-01-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0010_profiloatleta_immagine_profilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloatleta',
            name='mostra_peso',
            field=models.BooleanField(default=True, verbose_name='Mostra peso in classifica'),
        ),
    ]
