# Generated by Django 6.0.1 on 2026-01-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0011_profiloatleta_mostra_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='gap_passo',
            field=models.FloatField(blank=True, help_text='Passo GAP in m/s', null=True),
        ),
    ]
