# Generated by Django 6.0.1 on 2026-01-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0012_attivita_gap_passo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloatleta',
            name='dashboard_pubblica',
            field=models.BooleanField(default=False, verbose_name='Rendi dashboard pubblica'),
        ),
    ]
