# Generated by Django 6.0.1 on 2026-01-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0013_profiloatleta_dashboard_pubblica'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='vam_selettiva',
            field=models.FloatField(blank=True, help_text='VAM calcolata su pendenze > 7%', null=True),
        ),
    ]
