# Generated by Django 6.0.1 on 2026-01-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0014_attivita_vam_selettiva'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(choices=[('ricalcolo_vam_notturno', 'Ricalcolo VAM'), ('ricalcolo_stats_notturno', 'Ricalcolo Statistiche'), ('scrape_itra_utmb_settimanale', 'Scraping ITRA/UTMB'), ('pulizia_log_settimanale', 'Pulizia Log')], max_length=50, unique=True, verbose_name='Task')),
                ('active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('hour', models.CharField(default='*', max_length=10, verbose_name='Ora (0-23 o *)')),
                ('minute', models.CharField(default='0', max_length=10, verbose_name='Minuto (0-59 o *)')),
                ('day_of_week', models.CharField(default='*', max_length=20, verbose_name='Giorno (mon,tue... o *)')),
            ],
            options={
                'verbose_name': 'Configurazione Scheduler',
                'verbose_name_plural': 'Configurazione Scheduler',
            },
        ),
    ]
