# Generated by Django 6.0.1 on 2026-01-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0015_tasksettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksettings',
            name='manual_trigger',
            field=models.BooleanField(default=False, verbose_name='Esecuzione Manuale Richiesta'),
        ),
    ]
