# Generated by Django 6.0.1 on 2026-01-26 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0016_tasksettings_manual_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksettings',
            name='task_id',
            field=models.CharField(choices=[('ricalcolo_vam_notturno', 'Ricalcolo VAM'), ('ricalcolo_stats_notturno', 'Ricalcolo Statistiche'), ('scrape_itra_utmb_settimanale', 'Scraping ITRA/UTMB'), ('pulizia_log_settimanale', 'Pulizia Log'), ('sync_strava_periodico', 'Sync Strava Automatico')], max_length=50, unique=True, verbose_name='Task'),
        ),
    ]
