# Generated by Django 6.0.1 on 2026-01-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0017_alter_tasksettings_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='nome',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='attivita',
            name='workout_type',
            field=models.IntegerField(blank=True, help_text='1=Gara, 2=Lungo, 3=Lavoro', null=True),
        ),
    ]
