# Generated by Django 6.0.1 on 2026-01-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0018_attivita_nome_attivita_workout_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloatleta',
            name='data_fc_max',
            field=models.DateField(blank=True, null=True, verbose_name='Data rilevamento FC Max'),
        ),
        migrations.AddField(
            model_name='profiloatleta',
            name='fc_max_manuale',
            field=models.BooleanField(default=False, verbose_name='FC Max impostata manualmente'),
        ),
    ]
