# Generated by Django 6.0.1 on 2026-01-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0019_profiloatleta_data_fc_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloatleta',
            name='data_ultima_sincronizzazione',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultima Sincronizzazione Strava'),
        ),
        migrations.AddField(
            model_name='profiloatleta',
            name='data_ultimo_ricalcolo_statistiche',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ultimo Ricalcolo Statistiche'),
        ),
    ]
