# Generated by Django 6.0.1 on 2026-01-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0020_profiloatleta_data_ultima_sincronizzazione_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloatleta',
            name='peso_manuale',
            field=models.BooleanField(default=False, verbose_name='Peso impostato manualmente'),
        ),
    ]
