# Generated by Django 6.0.1 on 2026-01-30 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0022_logsistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloatleta',
            name='condividi_metriche',
            field=models.BooleanField(default=True, verbose_name='Condividi VO2max e Indici nel riepilogo'),
        ),
        migrations.AddField(
            model_name='profiloatleta',
            name='importa_attivita_private',
            field=models.BooleanField(default=False, verbose_name='Importa attività private da Strava'),
        ),
    ]
