# Generated by Django 6.0.1 on 2026-02-01 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0024_alter_tasksettings_task_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scarpa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.CharField(max_length=50, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('distanza', models.FloatField(default=0.0)),
                ('primary', models.BooleanField(default=False)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('modello_normalizzato', models.CharField(blank=True, max_length=200, null=True)),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scarpe', to='atleti.profiloatleta')),
            ],
            options={
                'verbose_name_plural': 'Scarpe',
                'ordering': ['-distanza'],
            },
        ),
    ]
