# Generated by Django 6.0.1 on 2026-02-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0025_scarpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='scarpa',
            name='retired',
            field=models.BooleanField(default=False, verbose_name='Dismessa'),
        ),
    ]
