# Generated by Django 6.0.1 on 2026-02-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0027_add_hide_home_notice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profiloatleta',
            options={'permissions': [('access_riepilogo', 'Può accedere al Riepilogo Atleti'), ('access_coach_dashboard', 'Può accedere alla Dashboard Coach'), ('access_confronto', 'Può accedere al Confronto'), ('access_attrezzatura', "Può accedere all'Attrezzatura"), ('access_gare', 'Può accedere alle Gare'), ('access_grafici', 'Può accedere ai Grafici')]},
        ),
    ]
