# Generated by Django 6.0.1 on 2026-02-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0028_alter_profiloatleta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='piazzamento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Posizione in classifica'),
        ),
    ]
