# Generated by Django 6.0.1 on 2026-02-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0029_attivita_piazzamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='dispositivo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dispositivo GPS'),
        ),
    ]
