# Generated by Django 6.0.1 on 2026-02-08 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0030_attivita_dispositivo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Allenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField(blank=True)),
                ('data_orario', models.DateTimeField()),
                ('distanza_km', models.FloatField()),
                ('dislivello', models.IntegerField(default=0, help_text='Dislivello positivo in metri')),
                ('tipo', models.CharField(choices=[('Trail', 'Trail Running'), ('Strada', 'Corsa su Strada')], default='Strada', max_length=10)),
                ('tempo_stimato', models.DurationField(help_text='Tempo previsto (HH:MM:SS)')),
                ('file_gpx', models.FileField(blank=True, null=True, upload_to='gpx_tracks/')),
                ('visibilita', models.CharField(choices=[('Pubblico', 'Pubblico (Tutti)'), ('Privato', 'Privato (Solo Invitati)')], default='Pubblico', max_length=10)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('creatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allenamenti_creati', to=settings.AUTH_USER_MODEL)),
                ('invitati', models.ManyToManyField(blank=True, related_name='inviti_allenamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Allenamenti',
                'ordering': ['-data_orario'],
            },
        ),
        migrations.CreateModel(
            name='CommentoAllenamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testo', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('allenamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenti', to='atleti.allenamento')),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partecipazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('Richiesta', 'In Attesa'), ('Approvata', 'Approvata'), ('Rifiutata', 'Rifiutata')], default='Richiesta', max_length=10)),
                ('motivo_rifiuto', models.TextField(blank=True, null=True)),
                ('is_at_risk', models.BooleanField(default=False)),
                ('risk_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('data_richiesta', models.DateTimeField(auto_now_add=True)),
                ('allenamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partecipanti', to='atleti.allenamento')),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('allenamento', 'atleta')},
            },
        ),
    ]
