# Generated by Django 6.0.2 on 2026-02-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0031_allenamento_commentoallenamento_partecipazione'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allenamento',
            name='file_gpx',
            field=models.FileField(blank=True, null=True, upload_to='gpx_track/'),
        ),
    ]
