# Generated by Django 6.0.2 on 2026-02-08 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0032_alter_allenamento_file_gpx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messaggio', models.CharField(max_length=255)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('letta', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(default='info', max_length=20)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifiche', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_creazione'],
            },
        ),
    ]
