# Generated by Django 6.0.2 on 2026-02-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0033_notifica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksettings',
            name='task_id',
            field=models.CharField(choices=[('ricalcolo_vam_notturno', 'Ricalcolo VAM'), ('ricalcolo_stats_notturno', 'Ricalcolo Statistiche'), ('scrape_itra_utmb_settimanale', 'Scraping ITRA/UTMB'), ('pulizia_log_settimanale', 'Pulizia Log'), ('sync_strava_periodico', 'Sync Strava Automatico'), ('repair_strava_settimanale', 'Riparazione Strava (Self-Healing)'), ('aggiorna_podio_ai_4h', 'Aggiornamento Podio AI')], max_length=50, unique=True, verbose_name='Task'),
        ),
    ]
