# Generated by Django 6.0.2 on 2026-02-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0034_alter_tasksettings_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloatleta',
            name='escludi_statistiche_coach',
            field=models.BooleanField(default=False, verbose_name='Escludimi dalle statistiche Coach'),
        ),
    ]
