# Generated by Django 6.0.2 on 2026-02-11 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0035_profiloatleta_escludi_statistiche_coach'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descrizione', models.TextField(blank=True)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='team_images/')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('creatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_creati', to=settings.AUTH_USER_MODEL)),
                ('membri', models.ManyToManyField(blank=True, related_name='teams_appartenenza', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profiloatleta',
            name='team_preferito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utenti_preferiti', to='atleti.team'),
        ),
        migrations.CreateModel(
            name='RichiestaAdesioneTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('In Attesa', 'In Attesa'), ('Approvata', 'Approvata'), ('Rifiutata', 'Rifiutata')], default='In Attesa', max_length=20)),
                ('data_richiesta', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste_adesione', to='atleti.team')),
            ],
            options={
                'unique_together': {('team', 'utente')},
            },
        ),
    ]
