# Generated by Django 6.0.2 on 2026-02-11 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0036_team_profiloatleta_team_preferito_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allenamento',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allenamenti', to='atleti.team'),
        ),
        migrations.AddField(
            model_name='richiestaadesioneteam',
            name='tipo',
            field=models.CharField(choices=[('Adesione', 'Richiesta Utente'), ('Invito', 'Invito Creatore')], default='Adesione', max_length=10),
        ),
        migrations.AlterField(
            model_name='allenamento',
            name='visibilita',
            field=models.CharField(choices=[('Pubblico', 'Pubblico (Tutti)'), ('Privato', 'Privato (Solo Invitati)'), ('Gruppo', 'Solo Gruppo')], default='Pubblico', max_length=10),
        ),
    ]
