# Generated by Django 6.0.2 on 2026-02-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0037_allenamento_team_richiestaadesioneteam_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partecipazione',
            name='esito_feedback',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='partecipazione',
            name='feedback_processato',
            field=models.BooleanField(default=False, verbose_name='Feedback Calcolato'),
        ),
        migrations.AddField(
            model_name='profiloatleta',
            name='allenamenti_saltati',
            field=models.IntegerField(default=0, verbose_name='Allenamenti Saltati'),
        ),
        migrations.AddField(
            model_name='profiloatleta',
            name='punteggio_feedback',
            field=models.IntegerField(default=0, verbose_name='Punteggio Affidabilità'),
        ),
        migrations.AlterField(
            model_name='tasksettings',
            name='task_id',
            field=models.CharField(choices=[('ricalcolo_vam_notturno', 'Ricalcolo VAM'), ('ricalcolo_stats_notturno', 'Ricalcolo Statistiche'), ('scrape_itra_utmb_settimanale', 'Scraping ITRA/UTMB'), ('pulizia_log_settimanale', 'Pulizia Log'), ('sync_strava_periodico', 'Sync Strava Automatico'), ('repair_strava_settimanale', 'Riparazione Strava (Self-Healing)'), ('aggiorna_podio_ai_4h', 'Aggiornamento Podio AI'), ('calcola_feedback_allenamenti', 'Calcolo Feedback Presenze')], max_length=50, unique=True, verbose_name='Task'),
        ),
    ]
