# Generated by Django 6.0.2 on 2026-02-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0038_partecipazione_esito_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partecipazione',
            name='motivo_rinuncia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partecipazione',
            name='stato',
            field=models.CharField(choices=[('Richiesta', 'In Attesa'), ('Approvata', 'Approvata'), ('Rifiutata', 'Rifiutata'), ('Rinuncia', 'Rinuncia')], default='Richiesta', max_length=10),
        ),
    ]
