# Generated by Django 6.0.2 on 2026-02-15 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0039_partecipazione_motivo_rinuncia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='allenamento',
            name='latitudine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allenamento',
            name='longitudine',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='allenamento',
            name='luogo',
            field=models.CharField(blank=True, help_text='Es. Città, Via o Parcheggio', max_length=100, null=True, verbose_name='Luogo di Ritrovo'),
        ),
    ]
