# Generated by Django 6.0.2 on 2026-02-15 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0040_allenamento_latitudine_allenamento_longitudine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiloatleta',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Foto Profilo Manuale'),
        ),
    ]
