# Generated by Django 6.0.2 on 2026-02-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0041_profiloatleta_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='allenamento',
            name='indirizzo',
            field=models.CharField(blank=True, help_text='Es. Via Roma 10 (Opzionale)', max_length=200, null=True, verbose_name='Indirizzo Specifico'),
        ),
        migrations.AlterField(
            model_name='allenamento',
            name='luogo',
            field=models.CharField(blank=True, help_text='Es. Parma, Parco Ducale', max_length=100, null=True, verbose_name='Luogo (Città/Zona)'),
        ),
    ]
