# Generated by Django 6.0.2 on 2026-02-16 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0042_allenamento_indirizzo_alter_allenamento_luogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='attivita',
            name='parziali',
            field=models.JSONField(blank=True, null=True, verbose_name='Parziali (Splits)'),
        ),
    ]
