# Generated by Django 6.0.4 on 2026-04-26 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atleti', '0043_attivita_parziali'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotazioneParchetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_richiedente', models.CharField(max_length=100)),
                ('titolo_evento', models.CharField(max_length=200)),
                ('data_orario_inizio', models.DateTimeField()),
                ('data_orario_fine', models.DateTimeField()),
                ('descrizione', models.TextField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Prenotazioni Parchetto',
                'ordering': ['-data_orario_inizio'],
            },
        ),
    ]
