# Generated by Django 6.0.4 on 2026-09-06 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campionato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Es. CSI Parma Primavera', max_length=100)),
                ('categoria', models.CharField(choices=[('2009/2010', 'Allievi (2009/2010)'), ('2011/2012', 'Giovanissimi (2011/2012)'), ('2013/2014', 'Esordienti (2013/2014)')], max_length=20)),
                ('stagione', models.CharField(default='2026/2027', max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Campionati',
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_squadra', models.CharField(choices=[('2009/2010', 'Allievi (2009/2010)'), ('2011/2012', 'Giovanissimi (2011/2012)'), ('2013/2014', 'Esordienti (2013/2014)')], max_length=20, verbose_name='Squadra Interessata')),
                ('tipo', models.CharField(choices=[('Allenamento', 'Allenamento'), ('Partita', 'Partita di Campionato'), ('Amichevole', 'Partita Amichevole')], default='Allenamento', max_length=20)),
                ('data', models.DateTimeField()),
                ('luogo', models.CharField(blank=True, default='Campo Sportivo', max_length=150, null=True)),
                ('avversario', models.CharField(blank=True, max_length=150, null=True)),
                ('in_casa', models.BooleanField(default=True)),
                ('gol_nostri', models.IntegerField(blank=True, null=True)),
                ('gol_avversari', models.IntegerField(blank=True, null=True)),
                ('note_evento', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Eventi (Calendario)',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Giocatore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cognome', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('2009/2010', 'Allievi (2009/2010)'), ('2011/2012', 'Giovanissimi (2011/2012)'), ('2013/2014', 'Esordienti (2013/2014)')], max_length=20)),
                ('telefono_giocatore', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono_genitore', models.CharField(blank=True, help_text='Specifica anche il nome se necessario', max_length=20, null=True)),
                ('scadenza_certificato', models.DateField(blank=True, null=True, verbose_name='Scadenza Certificato Medico')),
                ('attivo', models.BooleanField(default=True)),
                ('note_mediche', models.TextField(blank=True, help_text='Allergie, infortuni pregressi, ecc.', null=True)),
            ],
            options={
                'verbose_name_plural': 'Giocatori',
                'ordering': ['categoria', 'nome_cognome'],
            },
        ),
        migrations.CreateModel(
            name='SquadraClassifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_squadra', models.CharField(max_length=150)),
                ('is_nostra_squadra', models.BooleanField(default=False)),
                ('punti', models.IntegerField(default=0)),
                ('partite_giocate', models.IntegerField(default=0)),
                ('vittorie', models.IntegerField(default=0)),
                ('pareggi', models.IntegerField(default=0)),
                ('sconfitte', models.IntegerField(default=0)),
                ('gol_fatti', models.IntegerField(default=0)),
                ('gol_subiti', models.IntegerField(default=0)),
                ('campionato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squadre', to='squadra_calcio.campionato')),
            ],
            options={
                'verbose_name_plural': 'Voci Classifica',
                'ordering': ['-punti', '-gol_fatti'],
            },
        ),
        migrations.CreateModel(
            name='Presenza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('situazione', models.CharField(blank=True, help_text='Es. Infortunato, Malato, Assente ingiustificato', max_length=100, null=True)),
                ('minuti_giocati', models.IntegerField(blank=True, help_text='Compilare se è una Partita', null=True)),
                ('data_registrazione', models.DateTimeField(auto_now=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenze_registrate', to='squadra_calcio.evento')),
                ('giocatore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presenze', to='squadra_calcio.giocatore')),
                ('registrato_da', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Presenze',
                'unique_together': {('giocatore', 'evento')},
            },
        ),
    ]
