# Generated by Django 6.0.4 on 2026-09-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_calcio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenza',
            name='registrato_da',
        ),
        migrations.AddField(
            model_name='giocatore',
            name='modulo_golee_compilato',
            field=models.BooleanField(default=False, verbose_name='Modulo Golee'),
        ),
        migrations.AddField(
            model_name='presenza',
            name='firma_dispositivo',
            field=models.CharField(blank=True, help_text="Nome inserito nell'app", max_length=100, null=True),
        ),
    ]
