# Generated by Django 6.0.4 on 2026-09-06 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_calcio', '0002_remove_presenza_registrato_da_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giocatore',
            name='telefono_genitore',
            field=models.CharField(blank=True, help_text='Specifica anche il nome se necessario', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='giocatore',
            name='telefono_giocatore',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
