# Generated by Django 6.0.4 on 2026-09-09 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_calcio', '0003_alter_giocatore_telefono_genitore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giocatore',
            name='scadenza_carta_identita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giocatore',
            name='scadenza_visita_medica',
            field=models.DateField(blank=True, null=True),
        ),
    ]
