# Generated by Django 6.0.4 on 2026-09-09 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_calcio', '0004_giocatore_scadenza_carta_identita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giocatore',
            name='tessera_csi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='giocatore',
            name='tessera_figc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
