# Generated by Django 6.0.4 on 2026-09-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_calcio', '0005_giocatore_tessera_csi_giocatore_tessera_figc'),
    ]

    operations = [
        migrations.AddField(
            model_name='giocatore',
            name='data_nascita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giocatore',
            name='ruolo',
            field=models.CharField(choices=[('Giocatore', 'Giocatore'), ('Allenatore', 'Allenatore'), ('Dirigente', 'Dirigente')], default='Giocatore', max_length=50),
        ),
    ]
