# Generated by Django 6.0.4 on 2026-09-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_calcio', '0006_giocatore_data_nascita_giocatore_ruolo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora', models.DateTimeField(auto_now_add=True)),
                ('utente', models.CharField(max_length=100)),
                ('azione', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-data_ora'],
            },
        ),
    ]
