# Generated by Django 6.0.4 on 2026-09-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_calcio', '0007_logmodifica'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllarmeAck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('giocatore_id', models.IntegerField()),
                ('chiave_allarme', models.CharField(max_length=100)),
                ('data_ack', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Risultato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=50)),
                ('data_partita', models.DateField()),
                ('avversario', models.CharField(max_length=150)),
                ('gol_fatti', models.IntegerField(default=0)),
                ('gol_subiti', models.IntegerField(default=0)),
                ('marcatori', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
