# Generated by Django 6.1.1 on 2026-09-18 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_calcio', '0008_allarmeack_risultato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrenotazioneCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ora_inizio', models.DateTimeField()),
                ('data_ora_fine', models.DateTimeField()),
                ('categoria_richiedente', models.CharField(max_length=50)),
                ('avversario', models.CharField(max_length=100)),
                ('stato', models.CharField(default='In Attesa', max_length=20)),
                ('richiedente', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SegnalazioneScouting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('squadra_avversaria', models.CharField(max_length=100)),
                ('categoria_avversaria', models.CharField(max_length=50)),
                ('nome_giocatore', models.CharField(max_length=100)),
                ('note', models.TextField()),
                ('segnalatore', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProfiloMister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria_gestita', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
