# Generated by Django 6.1.1 on 2026-09-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_calcio', '0009_prenotazionecampo_segnalazionescouting_profilomister'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispositivoToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utente', models.CharField(max_length=50)),
                ('token_fcm', models.TextField(unique=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
