# Generated by Django 6.1.1 on 2026-09-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_calcio', '0010_dispositivotoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogConnessione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utente', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
                ('endpoint', models.CharField(max_length=255)),
                ('metodo', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('data_ora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_ora'],
            },
        ),
    ]
