# Generated by Django 6.1.1 on 2026-09-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_calcio', '0011_logconnessione'),
    ]

    operations = [
        migrations.CreateModel(
            name='CacheApi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=50)),
                ('payload_json', models.TextField()),
                ('ultima_modifica', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('endpoint', 'categoria')},
            },
        ),
    ]
