# Generated by Django 6.1.1 on 2026-09-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_calcio', '0012_cacheapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campionato',
            name='categoria',
            field=models.CharField(choices=[('LAB', 'LAB (Prima Squadra/Generico)'), ('LAB Under 17-18', 'LAB Under 17-18'), ('LAB Under 15-16', 'LAB Under 15-16'), ('LAB Under 13-14', 'LAB Under 13-14')], max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria_squadra',
            field=models.CharField(choices=[('LAB', 'LAB (Prima Squadra/Generico)'), ('LAB Under 17-18', 'LAB Under 17-18'), ('LAB Under 15-16', 'LAB Under 15-16'), ('LAB Under 13-14', 'LAB Under 13-14')], max_length=20, verbose_name='Squadra Interessata'),
        ),
        migrations.AlterField(
            model_name='giocatore',
            name='categoria',
            field=models.CharField(choices=[('LAB', 'LAB (Prima Squadra/Generico)'), ('LAB Under 17-18', 'LAB Under 17-18'), ('LAB Under 15-16', 'LAB Under 15-16'), ('LAB Under 13-14', 'LAB Under 13-14')], max_length=20),
        ),
    ]
