# Generated by Django 6.1.1 on 2026-09-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_calcio', '0013_alter_campionato_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campionato',
            name='categoria',
            field=models.CharField(choices=[('2009/2010', 'Allievi (2009/2010)'), ('2011/2012', 'Giovanissimi (2011/2012)'), ('2013/2014', 'Esordienti (2013/2014)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='evento',
            name='categoria_squadra',
            field=models.CharField(choices=[('2009/2010', 'Allievi (2009/2010)'), ('2011/2012', 'Giovanissimi (2011/2012)'), ('2013/2014', 'Esordienti (2013/2014)')], max_length=20, verbose_name='Squadra Interessata'),
        ),
        migrations.AlterField(
            model_name='giocatore',
            name='categoria',
            field=models.CharField(choices=[('2009/2010', 'Allievi (2009/2010)'), ('2011/2012', 'Giovanissimi (2011/2012)'), ('2013/2014', 'Esordienti (2013/2014)')], max_length=20),
        ),
    ]
