# Generated by Django 6.1.1 on 2026-09-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_calcio', '0014_alter_campionato_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risultato',
            name='convalidata',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='risultato',
            name='giornata',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='risultato',
            name='in_casa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='risultato',
            name='orario',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
