# Generated by Django 6.1.1 on 2026-09-26 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squadra_calcio', '0015_risultato_convalidata_risultato_giornata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='giocatore',
            name='codice_fiscale',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
